#!/usr/bin/env node

var args = process.argv.slice(2)

if (!args.length) args = ['Root']

for (var store of args) {
  for (var i = 1; i <= 3; ++i) {
    console.log(Buffer.from(store + "#" + i, 'binary').toString('hex'))
  }
}
