// Generated by CoffeeScript 1.12.2

/*
FFI interface to crypt32.dll
 */
var Ctx, HCertStore, ffi, k, pCtx, ref, ref1, struct, v;

ffi = require('ffi');

ref = require('ref');

struct = require('ref-struct');

Ctx = struct({
  dwCertEncodingType: 'long',
  pbCertEncoded: 'pointer',
  cbCertEncoded: 'long',
  pCertInfo: 'pointer',
  hCertStore: HCertStore = ref.refType(ref.types["void"])
});

pCtx = ref.refType(Ctx);

ref1 = require('./ctx');
for (k in ref1) {
  v = ref1[k];
  Ctx.prototype[k] = v;
}

module.exports = ffi.Library('crypt32', {
  CertOpenSystemStoreA: [HCertStore, ['pointer', 'string']],
  CertCloseStore: ['int', [HCertStore, 'long']],
  CertEnumCertificatesInStore: [pCtx, [HCertStore, pCtx]]
});
