// Generated by CoffeeScript 1.12.2

/*
Helper functions for Win32 certificate context
 */
var asn1, forge, pki;

forge = require('node-forge');

asn1 = forge.asn1;

pki = forge.pki;

this.crt = function() {
  var res;
  res = this.pbCertEncoded.reinterpret(this.cbCertEncoded);
  res = asn1.fromDer(res.toString('binary'));
  return pki.certificateFromAsn1(res);
};

this.pem = function() {
  return pki.certificateToPem(this.crt());
};
