// Generated by CoffeeScript 1.12.2

/*
Helper functions for Win32 certificate context
 */
var asn1, forge, pki;

forge = require('node-forge');

asn1 = forge.asn1;

pki = forge.pki;

this.crt = function() {
  var der;
  der = this.pbCertEncoded.reinterpret(this.cbCertEncoded);
  return pki.certificateFromAsn1(asn1.fromDer(der.toString('binary')));
};

this.pem = function() {
  return pki.certificateToPem(this.crt());
};
