// Generated by CoffeeScript 1.12.2

/*
Enumerate system root CAs synchronously
 */
var crypt;

crypt = require('./crypt32');

module.exports = function(cb) {
  var ctx, store;
  store = crypt.CertOpenSystemStoreA(null, 'ROOT');
  try {
    ctx = null;
    while (1) {
      ctx = crypt.CertEnumCertificatesInStore(store, ctx);
      if (ctx.isNull()) {
        break;
      }
      cb(ctx.deref().pem());
    }
  } finally {
    crypt.CertCloseStore(store, 0);
  }
};
