// Generated by CoffeeScript 1.12.2

/*
Format Certificate output
 */
var format, formats, oids;

module.exports = format = function(crt) {
  return formats(crt).join('\n');
};

formats = function(crt) {
  var k, ref, results, s, v;
  ref = require('./formats');
  results = [];
  for (k in ref) {
    v = ref[k];
    s = v(crt);
    if (v.join) {
      s = s.join(v.join);
    }
    if (!v.title) {
      s = (k.replace(/./, function(s) {
        return s.toUpperCase();
      })) + ": " + s;
    }
    results.push(s);
  }
  return results;
};

(format.oids = oids = function() {
  var i, k, len, list, ref, v;
  list = forge.oids;
  ref = require('./oids');
  for (v = i = 0, len = ref.length; i < len; v = ++i) {
    k = ref[v];
    list[v] = k;
    list[k] = v;
  }
})();
