// Generated by CoffeeScript 1.12.2

/*
Format parts of certificate
 */
var pem, pki, self, subject, valid;

pki = require('node-forge').pki;

self = require('../package');

this.subject;

subject = function(crt) {
  return crt.subject.attributes.map(function(rdn) {
    return "/" + (rdn.shortName || rdn.name || rdn.type) + "=" + rdn.value;
  });
};

subject.join = '';

this.valid = valid = function(crt) {
  var i, k, len, ref, results;
  ref = crt.validity;
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    k = ref[i];
    results.push(x[k].toISOString());
  }
  return results;
};

valid.join = ' - ';

this.saved = function() {
  return (new Date) + " by " + self.name + "@" + self.version;
};

this.pem = pem = function(crt) {
  return pki.certificateToPem(crt);
};

pem.title = false;
