// Generated by CoffeeScript 1.12.2

/*
X509_NAME_hash_old
 */
var asn1, crypto, forge, pki;

crypto = require('crypto');

forge = require('node-forge');

pki = forge.pki;

asn1 = forge.asn1;

module.exports = function(crt) {
  var md5;
  md5 = crypto.createHash('sha1');
  md5.update(asn1.toDer(pki.distinguishedNameToAsn1(crt.subject)));
  return md5.digest().readUInt32BE(0);
};
