// Generated by CoffeeScript 1.12.2

/*
X509_NAME_hash
 */
var asn1, canon, crypto, forge, pki, stripSeq;

crypto = require('crypto');

forge = require('node-forge');

pki = forge.pki;

asn1 = forge.asn1;

canon = function(subject) {
  return {
    attributes: subject.attributes.map(function(rdn) {
      return {
        valueTagClass: asn1.Type.UTF8,
        type: rdn.type,
        value: rdn.value.toLowerCase().replace(/\s+/g, ' ').replace(/^\s+|\s+$/, '')
      };
    })
  };
};

stripSeq = function(buffer) {
  buffer.getByte();
  asn1.getBerValueLength(buffer);
  return buffer.getBytes();
};

module.exports = function(crt) {
  var sha1;
  sha1 = crypto.createHash('sha1');
  sha1.update(stripSeq(asn1.toDer(pki.distinguishedNameToAsn1(canon(crt.subject)))));
  return sha1.digest().readUInt32BE(0);
};
